version: "3.9"

services:
  redis:
    image: redis:6.2.1-alpine

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: rails
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis
      DB_NAME: rails
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_HOST: db

    depends_on:
      - redis
      - sidekiq
      - db
